# Generated by Django 4.2.26 on 2025-11-25 15:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العقار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('property_type', models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('office', 'مكتب'), ('land', 'أرض'), ('commercial', 'تجاري'), ('duplex', 'دوبلكس'), ('studio', 'استوديو'), ('warehouse', 'مستودع'), ('building', 'عمارة')], default='apartment', max_length=20, verbose_name='نوع العقار')),
                ('status', models.CharField(choices=[('for_sale', 'للبيع'), ('for_rent', 'للإيجار'), ('reserved', 'محجوز'), ('rented', 'مؤجر'), ('sold', 'مباع'), ('unavailable', 'غير متاح')], default='for_sale', max_length=20, verbose_name='حالة العرض')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('area', models.CharField(blank=True, max_length=100, verbose_name='المنطقة')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='الشارع')),
                ('address', models.TextField(blank=True, verbose_name='العنوان التفصيلي')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='خط الطول')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر')),
                ('price_per_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='السعر لكل متر مربع')),
                ('is_negotiable', models.BooleanField(default=True, verbose_name='قابل للتفاوض')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المساحة (م²)')),
                ('bedrooms', models.PositiveIntegerField(default=0, verbose_name='غرف النوم')),
                ('bathrooms', models.PositiveIntegerField(default=0, verbose_name='الحمامات')),
                ('living_rooms', models.PositiveIntegerField(default=0, verbose_name='غرف المعيشة')),
                ('floors', models.PositiveIntegerField(default=1, verbose_name='عدد الطوابق')),
                ('floor_number', models.IntegerField(blank=True, null=True, verbose_name='رقم الطابق')),
                ('parking_spaces', models.PositiveIntegerField(default=0, verbose_name='مواقف السيارات')),
                ('furnishing', models.CharField(choices=[('furnished', 'مفروش'), ('semi_furnished', 'نصف مفروش'), ('unfurnished', 'غير مفروش')], default='unfurnished', max_length=20, verbose_name='حالة التأثيث')),
                ('year_built', models.PositiveIntegerField(blank=True, null=True, verbose_name='سنة البناء')),
                ('age_years', models.PositiveIntegerField(blank=True, null=True, verbose_name='عمر العقار')),
                ('owner_notes', models.TextField(blank=True, verbose_name='ملاحظات المالك')),
                ('agent_notes', models.TextField(blank=True, verbose_name='ملاحظات المسوق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('embedding', models.JSONField(blank=True, null=True, verbose_name='التضمين المتجهي')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agents.agent', verbose_name='المسوق العقاري')),
            ],
            options={
                'verbose_name': 'عقار',
                'verbose_name_plural': 'العقارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='properties/', verbose_name='الصورة')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='النص البديل')),
                ('is_primary', models.BooleanField(default=False, verbose_name='صورة رئيسية')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'صورة عقار',
                'verbose_name_plural': 'صور العقارات',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('deed', 'صك الملكية'), ('floor_plan', 'مخطط العقار'), ('license', 'رخصة البناء'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='documents/', verbose_name='الملف')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المستند')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
            },
        ),
        migrations.CreateModel(
            name='PropertyAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.CharField(choices=[('pool', 'مسبح'), ('garden', 'حديقة'), ('gym', 'صالة رياضية'), ('security', 'حراسة أمنية'), ('elevator', 'مصعد'), ('parking', 'موقف سيارات'), ('central_ac', 'تكييف مركزي'), ('balcony', 'شرفة'), ('maid_room', 'غرفة خادمة'), ('driver_room', 'غرفة سائق'), ('storage', 'مخزن'), ('kitchen', 'مطبخ'), ('laundry', 'غرفة غسيل'), ('internet', 'إنترنت'), ('satellite', 'قنوات فضائية'), ('intercom', 'اتصال داخلي'), ('cctv', 'كاميرات مراقبة'), ('playground', 'ملعب أطفال'), ('mosque', 'قريب من مسجد'), ('school', 'قريب من مدرسة'), ('mall', 'قريب من مول'), ('hospital', 'قريب من مستشفى'), ('sea_view', 'إطلالة بحرية'), ('city_view', 'إطلالة على المدينة')], max_length=50, verbose_name='الميزة')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'المميزات',
                'unique_together': {('property', 'amenity')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'neighborhood'], name='properties__city_27bef8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'status'], name='properties__propert_487234_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['agent', 'is_active'], name='properties__agent_i_184dad_idx'),
        ),
    ]
