# Generated by Django 4.2.26 on 2025-11-26 09:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video', models.FileField(upload_to='properties/videos/', verbose_name='الفيديو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='properties/thumbnails/', verbose_name='صورة مصغرة')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان الفيديو')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة (ثواني)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'فيديو عقار',
                'verbose_name_plural': 'فيديوهات العقارات',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
