# Generated by Django 4.2.26 on 2025-12-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertyvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='rent_period',
            field=models.CharField(choices=[('yearly', 'سنوي'), ('monthly', 'شهري'), ('daily', 'يومي')], default='yearly', help_text='سنوي/شهري/يومي - يُستخدم فقط للعقارات المعروضة للإيجار', max_length=20, verbose_name='فترة الإيجار'),
        ),
    ]
