# Generated by Django 4.2.26 on 2025-12-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_rent_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='interested_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المهتمين'),
        ),
    ]
