# Generated by Django 4.2.26 on 2025-12-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_add_interested_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reference_number',
            field=models.CharField(blank=True, help_text='رقم فريد للعقار يستخدمه الوكيل والعميل للتعريف', max_length=20, unique=True, verbose_name='الرقم المرجعي'),
        ),
    ]
