# Generated by Django 4.2.26 on 2025-12-11 00:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyViewingSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'الاثنين'), (1, 'الثلاثاء'), (2, 'الأربعاء'), (3, 'الخميس'), (4, 'الجمعة'), (5, 'السبت'), (6, 'الأحد')], verbose_name='يوم الأسبوع')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('slot_duration', models.PositiveIntegerField(default=30, help_text='مدة كل موعد معاينة بالدقائق', verbose_name='مدة الفترة (دقائق)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_slots', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'فترة معاينة',
                'verbose_name_plural': 'فترات المعاينة',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('property', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='PropertyViewingCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='وقت البداية')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='وقت النهاية')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_calendar', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'يوم تقويم',
                'verbose_name_plural': 'تقويم المعاينة',
                'ordering': ['date'],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
