# Generated by Django 4.2.26 on 2025-11-25 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('properties', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الجوال')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('qualified', 'مؤهل'), ('viewing_scheduled', 'موعد معاينة'), ('negotiating', 'قيد التفاوض'), ('won', 'تم البيع/التأجير'), ('lost', 'خسارة'), ('on_hold', 'معلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('source', models.CharField(choices=[('website_chat', 'شات الموقع'), ('whatsapp', 'واتساب'), ('phone', 'هاتف'), ('referral', 'إحالة'), ('social_media', 'وسائل التواصل'), ('other', 'أخرى')], default='website_chat', max_length=20, verbose_name='المصدر')),
                ('urgency', models.CharField(choices=[('immediate', 'فوري'), ('within_week', 'خلال أسبوع'), ('within_month', 'خلال شهر'), ('exploring', 'استكشاف فقط')], default='exploring', max_length=20, verbose_name='الاستعجال')),
                ('looking_for', models.CharField(choices=[('buy', 'شراء'), ('rent', 'إيجار'), ('both', 'كلاهما')], default='buy', max_length=20, verbose_name='يبحث عن')),
                ('property_type_preference', models.CharField(blank=True, max_length=100, verbose_name='نوع العقار المفضل')),
                ('city_preference', models.CharField(blank=True, max_length=100, verbose_name='المدينة المفضلة')),
                ('neighborhood_preference', models.CharField(blank=True, max_length=200, verbose_name='الأحياء المفضلة')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الحد الأدنى للميزانية')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الحد الأعلى للميزانية')),
                ('bedrooms_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للغرف')),
                ('bathrooms_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأدنى للحمامات')),
                ('size_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للمساحة')),
                ('special_requirements', models.TextField(blank=True, verbose_name='متطلبات خاصة')),
                ('preferred_contact_method', models.CharField(choices=[('phone', 'هاتف'), ('whatsapp', 'واتساب'), ('email', 'بريد إلكتروني')], default='phone', max_length=20, verbose_name='طريقة التواصل المفضلة')),
                ('preferred_contact_time', models.CharField(blank=True, max_length=100, verbose_name='وقت التواصل المفضل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('ai_summary', models.TextField(blank=True, verbose_name='ملخص AI')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='التقييم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('last_contact_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر تواصل')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='agents.agent', verbose_name='المسوق العقاري')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='chat.conversation', verbose_name='المحادثة')),
                ('interested_properties', models.ManyToManyField(blank=True, related_name='interested_leads', to='properties.property', verbose_name='العقارات المهتم بها')),
            ],
            options={
                'verbose_name': 'عميل محتمل',
                'verbose_name_plural': 'العملاء المحتملين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ViewingAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(verbose_name='التاريخ')),
                ('scheduled_time', models.TimeField(verbose_name='الوقت')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'تم'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('feedback', models.TextField(blank=True, verbose_name='التعليقات بعد المعاينة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_appointments', to='leads.lead', verbose_name='العميل')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewing_appointments', to='properties.property', verbose_name='العقار')),
            ],
            options={
                'verbose_name': 'موعد معاينة',
                'verbose_name_plural': 'مواعيد المعاينة',
                'ordering': ['scheduled_date', 'scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'تم الإنشاء'), ('status_changed', 'تغيير الحالة'), ('contacted', 'تم التواصل'), ('viewing', 'معاينة'), ('note_added', 'إضافة ملاحظة'), ('property_viewed', 'عرض عقار'), ('message_sent', 'إرسال رسالة')], max_length=20, verbose_name='نوع النشاط')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('metadata', models.JSONField(blank=True, null=True, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'نشاط',
                'verbose_name_plural': 'الأنشطة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['agent', 'status'], name='leads_lead_agent_i_69cbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
    ]
