# Generated by Django 4.2.26 on 2025-12-02 00:02

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(blank=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='whatsapp',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='واتساب'),
        ),
    ]
