# Generated by Django 4.2.26 on 2025-12-09 03:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_reference_number'),
        ('agents', '0008_agent_bot_contact_info_agent_bot_pricing_policy_and_more'),
        ('leads', '0002_alter_lead_email_alter_lead_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarBlockedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reason', models.CharField(choices=[('holiday', 'إجازة'), ('maintenance', 'صيانة'), ('reserved', 'محجوز'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='السبب')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_partial', models.BooleanField(default=False, verbose_name='حظر جزئي')),
                ('blocked_start_time', models.TimeField(blank=True, null=True, verbose_name='وقت بداية الحظر')),
                ('blocked_end_time', models.TimeField(blank=True, null=True, verbose_name='وقت نهاية الحظر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تاريخ محظور',
                'verbose_name_plural': 'التواريخ المحظورة',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyCalendar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_start_time', models.TimeField(default='09:00', verbose_name='وقت البداية الافتراضي')),
                ('default_end_time', models.TimeField(default='21:00', verbose_name='وقت النهاية الافتراضي')),
                ('slot_duration', models.PositiveIntegerField(default=30, verbose_name='مدة الفترة (دقائق)')),
                ('working_days', models.JSONField(default=dict, help_text='{"0": true, "1": true, "5": false, "6": false}', verbose_name='أيام العمل')),
                ('allow_ai_booking', models.BooleanField(default=True, verbose_name='السماح بالحجز من الوكيل الذكي')),
                ('max_bookings_per_day', models.PositiveIntegerField(default=10, verbose_name='الحد الأقصى للحجوزات يومياً')),
                ('min_advance_hours', models.PositiveIntegerField(default=2, verbose_name='الحد الأدنى للإشعار المسبق (ساعات)')),
                ('max_advance_days', models.PositiveIntegerField(default=30, verbose_name='الحد الأقصى للحجز المسبق (أيام)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تقويم عقار',
                'verbose_name_plural': 'تقويمات العقارات',
            },
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewing_appointments', to='agents.agent', verbose_name='المسوق العقاري'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='booked_by',
            field=models.CharField(choices=[('agent', 'المسوق'), ('ai_agent', 'الوكيل الذكي'), ('client', 'العميل')], default='agent', max_length=20, verbose_name='تم الحجز بواسطة'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='المدة (دقائق)'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الانتهاء'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='location',
            field=models.CharField(blank=True, max_length=500, verbose_name='موقع المعاينة'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='تقييم العميل'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='تم إرسال التذكير'),
        ),
        migrations.AddField(
            model_name='viewingappointment',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت إرسال التذكير'),
        ),
        migrations.AlterField(
            model_name='viewingappointment',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'تم'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر'), ('rescheduled', 'تم إعادة الجدولة')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AddIndex(
            model_name='viewingappointment',
            index=models.Index(fields=['property', 'scheduled_date'], name='leads_viewi_propert_10aa15_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingappointment',
            index=models.Index(fields=['agent', 'scheduled_date'], name='leads_viewi_agent_i_4ad4af_idx'),
        ),
        migrations.AddIndex(
            model_name='viewingappointment',
            index=models.Index(fields=['lead', 'status'], name='leads_viewi_lead_id_abbf76_idx'),
        ),
        migrations.AddField(
            model_name='propertycalendar',
            name='property',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='properties.property', verbose_name='العقار'),
        ),
        migrations.AddField(
            model_name='calendarblockeddate',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='leads.propertycalendar', verbose_name='التقويم'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarblockeddate',
            unique_together={('calendar', 'date')},
        ),
    ]
