# Generated by Django 4.2.26 on 2026-01-01 12:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_whatsapp_instance'),
        ('leads', '0003_calendarblockeddate_propertycalendar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'المستخدم'), ('assistant', 'الوكيل')], max_length=20, verbose_name='المرسل')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.whatsappinstance', verbose_name='حساب الواتساب')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='leads.lead', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'رسالة واتساب',
                'verbose_name_plural': 'رسائل الواتساب',
                'ordering': ['created_at'],
            },
        ),
    ]
