# Generated by Django 5.2.6 on 2026-02-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_whatsappmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='looking_for',
            field=models.CharField(blank=True, choices=[('buy', 'شراء'), ('rent', 'إيجار'), ('both', 'كلاهما')], default='', max_length=20, verbose_name='يبحث عن'),
        ),
    ]
