# Generated by Django 5.2.6 on 2026-02-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_fix_looking_for_default_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'جديد'), ('interested', 'مهتم'), ('contacted', 'تم التواصل'), ('viewing_scheduled', 'موعد معاينة'), ('qualified', 'مؤهل'), ('negotiating', 'قيد التفاوض'), ('converted', 'تم التحويل'), ('won', 'تم البيع/التأجير'), ('lost', 'خسارة'), ('on_hold', 'معلق')], default='new', max_length=20, verbose_name='الحالة'),
        ),
    ]
