# Generated by Django 4.2.26 on 2025-11-25 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الشركة')),
                ('license_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الترخيص')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='واتساب')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('logo', models.ImageField(blank=True, upload_to='agents/logos/', verbose_name='الشعار')),
                ('profile_image', models.ImageField(blank=True, upload_to='agents/profiles/', verbose_name='الصورة الشخصية')),
                ('bot_name', models.CharField(default='Newra AI', max_length=100, verbose_name='اسم البوت')),
                ('bot_welcome_message', models.TextField(default='مرحباً! أنا مساعد Newra Estate لمساعدتك في اختيار العقار المناسب. هل تبحث عن شراء أم استئجار عقار؟', verbose_name='رسالة الترحيب')),
                ('bot_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='لغة البوت')),
                ('notify_email', models.BooleanField(default=True, verbose_name='إشعارات البريد')),
                ('notify_whatsapp', models.BooleanField(default=False, verbose_name='إشعارات واتساب')),
                ('webhook_url', models.URLField(blank=True, verbose_name='رابط Webhook')),
                ('webhook_secret', models.CharField(blank=True, max_length=100, verbose_name='مفتاح Webhook')),
                ('subscription_plan', models.CharField(choices=[('free', 'مجاني'), ('basic', 'أساسي'), ('pro', 'احترافي'), ('enterprise', 'مؤسسي')], default='free', max_length=20, verbose_name='خطة الاشتراك')),
                ('subscription_expires', models.DateField(blank=True, null=True, verbose_name='انتهاء الاشتراك')),
                ('total_leads', models.PositiveIntegerField(default=0, verbose_name='إجمالي العملاء المحتملين')),
                ('total_conversations', models.PositiveIntegerField(default=0, verbose_name='إجمالي المحادثات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('is_verified', models.BooleanField(default=False, verbose_name='موثق')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مسوق عقاري',
                'verbose_name_plural': 'المسوقين العقاريين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(default='gpt-4o', max_length=50, verbose_name='نموذج AI')),
                ('ai_temperature', models.FloatField(default=0.7, verbose_name='درجة الإبداعية')),
                ('ai_max_tokens', models.PositiveIntegerField(default=2000, verbose_name='الحد الأقصى للكلمات')),
                ('custom_system_prompt', models.TextField(blank=True, verbose_name='تعليمات مخصصة')),
                ('forbidden_topics', models.TextField(blank=True, verbose_name='مواضيع محظورة')),
                ('auto_create_lead', models.BooleanField(default=True, verbose_name='إنشاء lead تلقائي')),
                ('lead_notification_threshold', models.CharField(choices=[('all', 'جميع المحادثات'), ('interested', 'المهتمين فقط'), ('ready', 'الجاهزين للشراء')], default='interested', max_length=20, verbose_name='عتبة الإشعار')),
                ('working_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية العمل')),
                ('working_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية العمل')),
                ('working_days', models.CharField(default='0,1,2,3,4', max_length=50, verbose_name='أيام العمل')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='agents.agent', verbose_name='المسوق')),
            ],
            options={
                'verbose_name': 'إعدادات المسوق',
                'verbose_name_plural': 'إعدادات المسوقين',
            },
        ),
    ]
