# Generated by Django 4.2.26 on 2025-11-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bot_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='لون البوت'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bot_personality',
            field=models.TextField(default='أنا مساعد عقاري ذكي ومحترف، أساعدك في العثور على العقار المناسب.', help_text='مثال: أنا سعود، مساعدك في شركة روشن العقارية', verbose_name='شخصية الوكيل'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bot_title',
            field=models.CharField(default='مساعدك العقاري الذكي', max_length=200, verbose_name='وصف الوكيل'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bot_name',
            field=models.CharField(default='نيورا', max_length=100, verbose_name='اسم الوكيل'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bot_welcome_message',
            field=models.TextField(default='مرحباً! 👋 كيف يمكنني مساعدتك اليوم في البحث عن عقارك المثالي؟', verbose_name='رسالة الترحيب'),
        ),
    ]
