# Generated by Django 4.2.26 on 2025-11-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_bot_color_agent_bot_personality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bot_collect_leads',
            field=models.BooleanField(default=True, help_text='السماح للوكيل بجمع بيانات العملاء المهتمين تلقائياً', verbose_name='جمع بيانات العملاء'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bot_system_prompt',
            field=models.TextField(blank=True, help_text='تعليمات مخصصة للوكيل الذكي. مثال: اسأل العميل عن رقم جواله إذا أبدى اهتمامه', verbose_name='تعليمات الوكيل (System Prompt)'),
        ),
    ]
