# Generated by Django 4.2.26 on 2025-12-01 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_add_bot_system_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='subscription_auto_renew',
            field=models.BooleanField(default=False, verbose_name='تجديد تلقائي'),
        ),
        migrations.AddField(
            model_name='agent',
            name='subscription_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء الاشتراك'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='subscription_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك'),
        ),
    ]
