# Generated by Django 4.2.26 on 2025-12-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_subscription_auto_renew_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_model', models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash - سريع جداً'), ('gemini-1.5-flash', 'Gemini 1.5 Flash - سريع'), ('gemini-1.5-pro', 'Gemini 1.5 Pro - متوازن'), ('gemini-2.5-pro-preview-05-06', 'Gemini 2.5 Pro - الأفضل جودة')], default='gemini-2.5-pro-preview-05-06', max_length=100, verbose_name='نموذج الذكاء الاصطناعي')),
                ('system_prompt', models.TextField(blank=True, help_text='التعليمات الأساسية التي تُطبق على جميع الوكلاء', verbose_name='System Prompt الأساسي')),
                ('default_rules', models.TextField(blank=True, help_text='قواعد إضافية للوكيل', verbose_name='القواعد العامة')),
                ('response_style', models.CharField(choices=[('professional', 'احترافي ومهني'), ('friendly', 'ودود وقريب'), ('formal', 'رسمي')], default='friendly', max_length=20, verbose_name='أسلوب الرد')),
                ('dialect', models.CharField(choices=[('saudi', 'سعودية'), ('gulf', 'خليجية'), ('formal_arabic', 'فصحى')], default='saudi', max_length=20, verbose_name='اللهجة')),
                ('ask_for_phone', models.BooleanField(default=True, verbose_name='طلب رقم الجوال')),
                ('show_prices', models.BooleanField(default=True, verbose_name='عرض الأسعار')),
                ('suggest_similar', models.BooleanField(default=True, verbose_name='اقتراح عقارات مشابهة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
