# Generated by Django 4.2.26 on 2025-12-02 00:02

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_globalsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=encrypted_model_fields.fields.EncryptedEmailField(verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='license_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='رقم الترخيص'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='phone',
            field=encrypted_model_fields.fields.EncryptedCharField(verbose_name='رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='whatsapp',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, verbose_name='واتساب'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ai_model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash - سريع جداً'), ('gemini-1.5-flash', 'Gemini 1.5 Flash - سريع'), ('gemini-1.5-pro', 'Gemini 1.5 Pro - متوازن'), ('gemini-2.5-pro-preview-05-06', 'Gemini 2.5 Pro - الأفضل جودة'), ('gemini-2.5-flash-preview-05-20', 'Gemini 2.5 Flash - الأحدث والأسرع'), ('gemini-3-pro-preview', 'Gemini 3 Pro - الجيل الثالث')], default='gemini-3-pro-preview', max_length=100, verbose_name='نموذج الذكاء الاصطناعي'),
        ),
    ]
