# Generated by Django 4.2.26 on 2025-12-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agent_email_alter_agent_license_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='تم التحقق من الإيميل'),
        ),
    ]
