# Generated by Django 4.2.26 on 2025-12-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_add_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='bot_contact_info',
            field=models.TextField(blank=True, help_text='مثال: واتساب: 05xxxxxxxx، الموقع: www.example.com', verbose_name='معلومات التواصل الإضافية'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bot_pricing_policy',
            field=models.TextField(blank=True, help_text='مثال: الأسعار قابلة للتفاوض، الدفع نقداً أو بالتقسيط', verbose_name='سياسة التسعير والدفع'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bot_services',
            field=models.TextField(blank=True, help_text='مثال: بيع، شراء، تأجير، إدارة أملاك', verbose_name='الخدمات المقدمة'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bot_viewing_policy',
            field=models.TextField(blank=True, help_text='مثال: المعاينة مجانية، الحجز بعربون 5%', verbose_name='سياسة المعاينة والحجز'),
        ),
        migrations.AddField(
            model_name='agent',
            name='bot_work_areas',
            field=models.TextField(blank=True, help_text='مثال: الرياض - حي النرجس، حي الياسمين', verbose_name='مناطق العمل'),
        ),
    ]
