# Generated by Django 4.2.26 on 2025-12-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_bot_contact_info_agent_bot_pricing_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT')], default='gemini', max_length=20, verbose_name='مزود الذكاء الاصطناعي'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='مفتاح API الخاص بـ OpenAI', max_length=500, verbose_name='مفتاح OpenAI API'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='openai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o - الأفضل'), ('gpt-4o-mini', 'GPT-4o Mini - سريع وموفر'), ('gpt-4-turbo', 'GPT-4 Turbo - متوازن'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo - اقتصادي')], default='gpt-4o-mini', max_length=100, verbose_name='نموذج OpenAI'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ai_model',
            field=models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash - سريع جداً'), ('gemini-1.5-flash', 'Gemini 1.5 Flash - سريع'), ('gemini-1.5-pro', 'Gemini 1.5 Pro - متوازن'), ('gemini-2.5-pro-preview-05-06', 'Gemini 2.5 Pro - الأفضل جودة'), ('gemini-2.5-flash-preview-05-20', 'Gemini 2.5 Flash - الأحدث والأسرع'), ('gemini-3-pro-preview', 'Gemini 3 Pro - الجيل الثالث')], default='gemini-3-pro-preview', max_length=100, verbose_name='نموذج Gemini'),
        ),
    ]
