# Generated by Django 4.2.26 on 2025-12-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_add_openai_support'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsettings',
            name='viewing_end_hour',
            field=models.PositiveIntegerField(default=21, help_text='الساعة التي تنتهي فيها المعاينات (مثال: 21 = 9 مساءً)', verbose_name='نهاية أوقات المعاينة'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='viewing_slot_duration',
            field=models.PositiveIntegerField(default=30, help_text='مدة كل موعد معاينة بالدقائق', verbose_name='مدة فترة المعاينة (بالدقائق)'),
        ),
        migrations.AddField(
            model_name='agentsettings',
            name='viewing_start_hour',
            field=models.PositiveIntegerField(default=8, help_text='الساعة التي تبدأ فيها المعاينات (مثال: 8 = 8 صباحاً)', verbose_name='بداية أوقات المعاينة'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bot_welcome_message',
            field=models.TextField(default='أهلاً وسهلاً! 👋', help_text='سيتم إضافة اسم الموظف والشركة تلقائياً', verbose_name='رسالة الترحيب'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='openai_model',
            field=models.CharField(choices=[('gpt-5', 'GPT-5 - الجيل الخامس 🚀'), ('gpt-5-mini', 'GPT-5 Mini - سريع وذكي ⚡'), ('gpt-5-mini-2025-08-07', 'GPT-5 Mini (2025-08-07) - الأحدث ⚡'), ('gpt-4.1', 'GPT-4.1 - الأحدث'), ('gpt-4o', 'GPT-4o - الأفضل'), ('gpt-4o-mini', 'GPT-4o Mini - سريع وموفر'), ('gpt-4-turbo', 'GPT-4 Turbo - متوازن'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo - اقتصادي')], default='gpt-4o-mini', max_length=100, verbose_name='نموذج OpenAI'),
        ),
    ]
