# Generated by Django 4.2.26 on 2025-12-11 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentsettings_viewing_end_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='google_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Google ID'),
        ),
    ]
