# Generated by Django 4.2.27 on 2025-12-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agent_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='التوكن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ الانتهاء')),
                ('used', models.BooleanField(default=False, verbose_name='مستخدم')),
            ],
            options={
                'verbose_name': 'توكن إعادة تعيين',
                'verbose_name_plural': 'توكنات إعادة التعيين',
            },
        ),
    ]
