# Generated by Django 4.2.27 on 2025-12-24 09:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_name', models.CharField(max_length=100, unique=True, verbose_name='اسم الـ Instance')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم الواتساب المربوط')),
                ('status', models.CharField(choices=[('disconnected', 'غير متصل'), ('connecting', 'جاري الاتصال'), ('connected', 'متصل'), ('qr_ready', 'QR جاهز')], default='disconnected', max_length=20, verbose_name='حالة الاتصال')),
                ('qr_code', models.TextField(blank=True, verbose_name='QR Code (Base64)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('auto_reply', models.BooleanField(default=True, verbose_name='رد تلقائي')),
                ('welcome_message', models.TextField(blank=True, help_text='رسالة ترسل تلقائياً عند أول تواصل', verbose_name='رسالة الترحيب')),
                ('away_message', models.TextField(blank=True, help_text='رسالة ترسل خارج أوقات العمل', verbose_name='رسالة الغياب')),
                ('messages_received', models.PositiveIntegerField(default=0, verbose_name='الرسائل المستلمة')),
                ('messages_sent', models.PositiveIntegerField(default=0, verbose_name='الرسائل المرسلة')),
                ('connected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاتصال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_instance', to='agents.agent', verbose_name='المسوق')),
            ],
            options={
                'verbose_name': 'ربط واتساب',
                'verbose_name_plural': 'ربط الواتساب',
            },
        ),
    ]
