# Generated by Django 5.2.6 on 2026-02-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_whatsapp_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='fal_license',
            field=models.CharField(blank=True, max_length=50, verbose_name='رخصة فال'),
        ),
    ]
