# Generated by Django 5.2.6 on 2026-02-15 01:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agent_fal_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_key', models.CharField(choices=[('monthly', 'شهري - 199 ريال'), ('quarterly', '3 أشهر - 537 ريال'), ('semi', '6 أشهر - 1,015 ريال'), ('annual', 'سنوي - 1,791 ريال')], default='monthly', max_length=20, verbose_name='الخطة')),
                ('status', models.CharField(choices=[('trial', 'فترة تجريبية'), ('active', 'نشط'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('pending', 'بانتظار الدفع')], default='trial', max_length=20, verbose_name='الحالة')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ')),
                ('trial_start', models.DateTimeField(blank=True, null=True, verbose_name='بداية التجربة')),
                ('trial_end', models.DateTimeField(blank=True, null=True, verbose_name='نهاية التجربة')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='بداية الاشتراك')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='نهاية الاشتراك')),
                ('payment_link_id', models.CharField(blank=True, max_length=200, verbose_name='معرف رابط الدفع')),
                ('payment_id', models.CharField(blank=True, max_length=200, verbose_name='معرف الدفعة')),
                ('invoice_id', models.CharField(blank=True, max_length=200, verbose_name='معرف الفاتورة')),
                ('subscription_id', models.CharField(blank=True, max_length=200, verbose_name='معرف الاشتراك في StreamPay')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='agents.agent', verbose_name='المسوق')),
            ],
            options={
                'verbose_name': 'اشتراك',
                'verbose_name_plural': 'الاشتراكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
