# Generated by Django 5.2.6 on 2026-02-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='ai_model',
            field=models.CharField(default='gpt-4o-mini', editable=False, max_length=100, verbose_name='النموذج المستخدم'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='ai_provider',
            field=models.CharField(default='openai', editable=False, max_length=20, verbose_name='مزود الذكاء الاصطناعي'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='openai_model',
            field=models.CharField(choices=[('gpt-4o', 'GPT-4o - الأفضل جودة 🧠'), ('gpt-4o-mini', 'GPT-4o Mini - سريع وموفر ⚡ (موصى به)'), ('gpt-4-turbo', 'GPT-4 Turbo - متوازن'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo - اقتصادي')], default='gpt-4o-mini', max_length=100, verbose_name='نموذج OpenAI'),
        ),
    ]
