# Generated by Django 5.2.6 on 2026-02-20 12:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_remove_gemini_use_openai_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsettings',
            name='ai_model',
            field=models.CharField(default='gpt-4.1-mini', editable=False, max_length=100, verbose_name='النموذج المستخدم'),
        ),
        migrations.AlterField(
            model_name='globalsettings',
            name='openai_model',
            field=models.CharField(choices=[('gpt-4.1', 'GPT-4.1 - الأفضل جودة 🧠'), ('gpt-4.1-mini', 'GPT-4.1 Mini - الأحدث والأذكى بسعر مناسب ⚡ (موصى به)'), ('gpt-4o', 'GPT-4o - ممتاز'), ('gpt-4o-mini', 'GPT-4o Mini - سريع وموفر'), ('gpt-4-turbo', 'GPT-4 Turbo - متوازن'), ('gpt-3.5-turbo', 'GPT-3.5 Turbo - اقتصادي')], default='gpt-4.1-mini', max_length=100, verbose_name='نموذج OpenAI'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_key',
            field=models.CharField(choices=[('trial_day', 'يوم تجريبي - 1 ريال'), ('monthly', 'شهري - 199 ريال'), ('quarterly', '3 أشهر - 537 ريال'), ('semi', '6 أشهر - 1,015 ريال'), ('annual', 'سنوي - 1,791 ريال')], default='monthly', max_length=20, verbose_name='الخطة'),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_tokens', models.PositiveIntegerField(default=0, verbose_name='توكنات الإدخال')),
                ('completion_tokens', models.PositiveIntegerField(default=0, verbose_name='توكنات الإخراج')),
                ('total_tokens', models.PositiveIntegerField(default=0, verbose_name='إجمالي التوكنات')),
                ('model', models.CharField(default='gpt-4.1-mini', max_length=50, verbose_name='النموذج')),
                ('source', models.CharField(choices=[('web_chat', 'محادثة الويب'), ('whatsapp', 'واتساب'), ('api', 'API')], default='web_chat', max_length=20, verbose_name='المصدر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='agents.agent', verbose_name='المسوق')),
            ],
            options={
                'verbose_name': 'استهلاك توكنات',
                'verbose_name_plural': 'استهلاك التوكنات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['agent', 'created_at'], name='agents_toke_agent_i_e78306_idx')],
            },
        ),
    ]
