# Generated by Django 5.2.6 on 2026-02-20 12:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_add_token_usage_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم المفتاح')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='المفتاح')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('last_used', models.DateTimeField(blank=True, null=True, verbose_name='آخر استخدام')),
                ('requests_count', models.PositiveIntegerField(default=0, verbose_name='عدد الطلبات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agents.agent', verbose_name='المسوق')),
            ],
            options={
                'verbose_name': 'مفتاح API',
                'verbose_name_plural': 'مفاتيح API',
                'ordering': ['-created_at'],
            },
        ),
    ]
