# Generated by Django 5.2.6 on 2026-02-20 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_add_api_key_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='اسم الـ Webhook')),
                ('url', models.URLField(max_length=500, verbose_name='رابط الاستقبال')),
                ('secret', models.CharField(blank=True, max_length=64, verbose_name='المفتاح السري (HMAC)')),
                ('events', models.JSONField(default=list, verbose_name='الأحداث المشترك بها')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('total_sent', models.PositiveIntegerField(default=0, verbose_name='إجمالي المرسل')),
                ('total_failed', models.PositiveIntegerField(default=0, verbose_name='إجمالي الفاشل')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر إرسال')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر نجاح')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to='agents.agent', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=50, verbose_name='الحدث')),
                ('payload', models.JSONField(verbose_name='البيانات المرسلة')),
                ('status', models.CharField(choices=[('success', 'نجاح'), ('failed', 'فشل'), ('pending', 'قيد الإرسال')], default='pending', max_length=10)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True, verbose_name='كود الاستجابة')),
                ('response_body', models.TextField(blank=True, verbose_name='نص الاستجابة')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='المدة (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.webhook', verbose_name='الـ Webhook')),
            ],
            options={
                'verbose_name': 'سجل Webhook',
                'verbose_name_plural': 'سجلات Webhook',
                'ordering': ['-created_at'],
            },
        ),
    ]
