# Generated by Django 5.2.6 on 2026-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='phone_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='هاش رقم الجوال'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_key',
            field=models.CharField(choices=[('monthly', 'شهري'), ('quarterly', '3 أشهر - 537 ريال'), ('semi', '6 أشهر - 1,015 ريال'), ('annual', 'سنوي - 1,791 ريال')], default='monthly', max_length=20, verbose_name='الخطة'),
        ),
    ]
