# Generated by Django 5.2.6 on 2026-02-27 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_add_phone_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tour_completed',
            field=models.BooleanField(default=False, verbose_name='أكمل جولة التعريف'),
        ),
    ]
