# Generated by Django 5.2.6 on 2026-02-27 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_add_tour_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('marketer', 'مسوق عقاري'), ('viewer', 'مشاهد فقط')], default='marketer', max_length=20, verbose_name='الدور')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('owner_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='agents.agent', verbose_name='المؤسسة الرئيسية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL, verbose_name='حساب العضو')),
            ],
            options={
                'verbose_name': 'عضو فريق',
                'verbose_name_plural': 'أعضاء الفريق',
                'ordering': ['-created_at'],
                'unique_together': {('owner_agent', 'user')},
            },
        ),
    ]
