# Generated by Django 5.2.6 on 2026-02-27 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='parent_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_subscriptions', to='agents.subscription', verbose_name='الاشتراك الرئيسي (المؤسسة)'),
        ),
    ]
