# Generated by Django 5.2.6 on 2026-02-28 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0024_subscription_parent_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='daily_inquiries',
            field=models.CharField(blank=True, choices=[('less_than_5', 'أقل من 5'), ('5_to_15', 'من 5 إلى 15'), ('15_to_30', 'من 15 إلى 30'), ('more_than_30', 'أكثر من 30')], max_length=20, verbose_name='عدد الاستفسارات اليومية في الواتساب'),
        ),
    ]
