# Generated by Django 4.2.27 on 2026-01-10 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ticket_number', models.CharField(max_length=20, unique=True, verbose_name='رقم التذكرة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('category', models.CharField(choices=[('bug', 'خطأ تقني'), ('feature', 'طلب ميزة'), ('question', 'استفسار'), ('complaint', 'شكوى'), ('other', 'أخرى')], default='bug', max_length=20, verbose_name='التصنيف')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد المراجعة'), ('resolved', 'تم الحل'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='رد الإدارة')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الرد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_tickets', to=settings.AUTH_USER_MODEL, verbose_name='تم الرد بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
    ]
