# Generated by Django 4.2.26 on 2025-11-25 15:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_id', models.CharField(max_length=100, verbose_name='معرف العميل')),
                ('client_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='رقم العميل')),
                ('source', models.CharField(choices=[('website', 'الموقع'), ('whatsapp', 'واتساب'), ('api', 'API')], default='website', max_length=20, verbose_name='المصدر')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('paused', 'متوقفة'), ('closed', 'مغلقة'), ('transferred', 'محولة')], default='active', max_length=20, verbose_name='الحالة')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='السياق')),
                ('extracted_preferences', models.JSONField(blank=True, default=dict, verbose_name='التفضيلات المستخرجة')),
                ('language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=5, verbose_name='اللغة')),
                ('messages_count', models.PositiveIntegerField(default=0, verbose_name='عدد الرسائل')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='بداية المحادثة')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='آخر رسالة')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='نهاية المحادثة')),
                ('user_agent', models.TextField(blank=True, verbose_name='معلومات المتصفح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.agent', verbose_name='المسوق العقاري')),
                ('discussed_properties', models.ManyToManyField(blank=True, related_name='conversations', to='properties.property', verbose_name='العقارات المناقشة')),
            ],
            options={
                'verbose_name': 'محادثة',
                'verbose_name_plural': 'المحادثات',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationSummary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary', models.TextField(verbose_name='الملخص')),
                ('key_points', models.JSONField(default=list, verbose_name='النقاط الرئيسية')),
                ('client_intent', models.CharField(blank=True, max_length=50, verbose_name='نية العميل')),
                ('budget_range', models.CharField(blank=True, max_length=100, verbose_name='نطاق الميزانية')),
                ('preferred_locations', models.JSONField(default=list, verbose_name='المواقع المفضلة')),
                ('property_requirements', models.JSONField(default=dict, verbose_name='متطلبات العقار')),
                ('lead_quality', models.CharField(choices=[('hot', 'ساخن'), ('warm', 'دافئ'), ('cold', 'بارد')], default='cold', max_length=20, verbose_name='جودة العميل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='chat.conversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'ملخص محادثة',
                'verbose_name_plural': 'ملخصات المحادثات',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'العميل'), ('assistant', 'المساعد'), ('system', 'النظام')], max_length=20, verbose_name='الدور')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('tool_calls', models.JSONField(blank=True, null=True, verbose_name='استدعاءات الأدوات')),
                ('tool_results', models.JSONField(blank=True, null=True, verbose_name='نتائج الأدوات')),
                ('model_used', models.CharField(blank=True, max_length=50, verbose_name='النموذج المستخدم')),
                ('tokens_used', models.PositiveIntegerField(default=0, verbose_name='الرموز المستخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الإرسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation', verbose_name='المحادثة')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['agent', 'status'], name='chat_conver_agent_i_a11f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['client_id'], name='chat_conver_client__cb914f_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['started_at'], name='chat_conver_started_7ca04e_idx'),
        ),
    ]
